# Python Homework 4


About Regular Expressions and Numpy


## HW 4-1. Regular Expressions (50 pts)
Instruction:

**1. (15pt)** 정규 표현식을 사용하여 다음 문제를 해결합니다.
아래에 제공된 리스트 `data`의 모든 숫자를 (정수, 소수 포함) 찾습니다. `data` 내부의 모든 요소는 $0$ 이상의 값을 가진다고 가정합니다.

**실행 결과** | Result:
```
>> 
['123.1', '4567', '789', '0.15', '257']
```

In [ ]:
# 1 
import re

data = ['apple', '123.1', 'orange', '4567', 'banana', '789', '0.15AB257']

# ========== your code here ==========



# ==========
print(num_list)

**2. (20pt)** 정규 표현식을 사용하여 아래 요구 사항에 따라 비밀번호를 매칭하고 매칭 결과 `True/False`를 출력합니다.

  - 입력한 비밀번호 길이는 `6-12`자리 여야 하며(`6과 12 포함`), `영문자`와 `숫자만` 입력할 수 있습니다.

**실행 결과** | Result: ({}는 사용자의 입력을 의미)
```
>> Enter your password: {123456}
   True
>> Enter your password: {QwerTyuiopas}
   True
>> Enter your password: {123Wert}
   True
>> Enter your password: {123w}
   False
>> Enter your password: {@#$%$%no}
   False
```
  

In [ ]:
# 2
import re

password = input('Enter your password: ')

# ========== your code here ==========


# ==========

**3. (15pt)** 아래에 주어진 리스트 `text`에서 각 string element마다 매 단어의 첫 글자를 따 약자를 생성하고자 합니다. 각 string element의 약자를 생성하여 `abbreviation` 리스트에 저장하여 출력하세요.

  - ex) World Health Organization -> WHO    

  
**실행 결과** | Result:
```
>>
['FEMA', 'IRA', 'DUP', 'FaDA', 'OoLC']
```
  

In [ ]:
# 3
import re

text = [
  'Federal Emergency Management Agency',
  'Irish Republican Army',
  'Democratic Unionist Party',
  'Food and Drug Administration',
  'Office of Legal Counsel'
]

# ========== your code here ==========



# ==========
print(abbreviations)

## HW 4-2. Numpy  (50 pts)

Instruction:

**1. (25pt)** Python의 **numpy**  패키지를 사용하여 다음 문제를 해결하세요:
* Numpy 패키지를 통해 $0 <= x < 1$의 난수값을 가지는 $5 \times 5$ 크기의 2차원 랜덤 균일분포 배열 `arr1`을 생성하세요. 
* 모든 요소가 동일한 정수값 $3$을 가지는 $5 \times 5$ 크기의 2차원 배열 `arr2`를 생성하세요.
* 두 배열 `arr1`과 `arr2`의 각 요소끼리 더하는 element-wise addition 연산을 진행한 후, `arr3`에 저장하여 출력하세요.
* `arr3`의 2번째 column을 인덱싱하여 출력하세요. (인덱스는 0부터 계산합니다)

**실행 결과 예시** | Result:
```
>>>
arr1:
 [[0.95761213 0.69412986 0.92702346 0.55211018 0.83383987]
 [0.65244204 0.88591894 0.87737734 0.65024589 0.21431809]
 [0.07652924 0.00835309 0.73029526 0.25944507 0.08023124]
 [0.3221819  0.96857493 0.24475053 0.37879287 0.59616885]
 [0.66984732 0.234567   0.77362569 0.53930924 0.51706774]]
arr2:
 [[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
arr3:
 [[3.95761213 3.69412986 3.92702346 3.55211018 3.83383987]
 [3.65244204 3.88591894 3.87737734 3.65024589 3.21431809]
 [3.07652924 3.00835309 3.73029526 3.25944507 3.08023124]
 [3.3221819  3.96857493 3.24475053 3.37879287 3.59616885]
 [3.66984732 3.234567   3.77362569 3.53930924 3.51706774]]
2nd column of arr3:
 [3.69412986 3.88591894 3.00835309 3.96857493 3.234567  ]
```

In [ ]:
# 1
# ========== your code here ==========
# create arr1


# create arr2


# add element-wise 


# 2nd column of arr3



**2. (25pt)** Python의 **numpy**  패키지를 사용하여 다음 문제를 해결하세요:
* 위에서 만든 $5 \times 5$ 배열 `arr3`의 처음 4개의 row를 선택하여 `reshape`을 통해 재구성하여 $10 \times 2$ 크기의 배열 `arr4`를 만드세요. 

* `arr4`의 각 row와 column의 평균을 출력하세요.
  - 각 row의 평균을 얻기 위해서는 가로 방향으로 평균이 구해져야 하며, 각 column의 평균을 얻기 위해서는 세로 방향으로 평균이 구해져야 합니다.

**실행 결과** | Result:
```
>>>
arr4:
 [[3.95761213 3.69412986]
 [3.92702346 3.55211018]
 [3.83383987 3.65244204]
 [3.88591894 3.87737734]
 [3.65024589 3.21431809]
 [3.07652924 3.00835309]
 [3.73029526 3.25944507]
 [3.08023124 3.3221819 ]
 [3.96857493 3.24475053]
 [3.37879287 3.59616885]]
arr4 mean of each row:
 [3.825871   3.73956682 3.74314095 3.88164814 3.43228199 3.04244116
 3.49487017 3.20120657 3.60666273 3.48748086]
arr4 mean of each column:
 [3.64890638 3.4421277 ]
```

In [ ]:
# 2
# ========== your code here ==========
# create arr4


# mean of each row


# mean of each column

